name: Markdown Quality Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    paths: ['**/*.md']

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Sprawdzanie jakości Markdown
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint Markdown files
        run: npm run lint:md-ci
        
      - name: Check Prettier formatting
        run: npx prettier --check "**/*.md"
        
      - name: Comment PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Wykryto problemy z formatowaniem Markdown. Uruchom `npm run fix:md` aby automatycznie poprawić błędy lub `npm run lint:md-ci` aby sprawdzić szczegóły.'
            })